Repository IntersectMBO/cardano-api, pull requests merged in 2024-10, with the labels that each got.

#647 Expose functions and types from `cardano-ledger-alonzo` and `cardano-ledger-byron` required by cardano-cli
  cardano-api/cardano-api.cabal
  cardano-api/internal/Cardano/Api/ReexposeLedger.hs
  cardano-api/internal/Cardano/Api/SpecialByron.hs
  cardano-api/src/Cardano/Api.hs
  cardano-api/src/Cardano/Api/Byron.hs
  cardano-api/test/cardano-api-test/Test/Cardano/Api/Transaction/Autobalance.hs
Labels: enhancement

#654 governance alignment updates
  CODE_OF_CONDUCT.md
  SECURITY.md
Labels: documentation

#656 Expose remaining functions and types from `cardano-ledger-*` required by `cardano-cli`
  cardano-api/gen/Test/Gen/Cardano/Api/Typed.hs
  cardano-api/internal/Cardano/Api/ReexposeLedger.hs
  cardano-api/src/Cardano/Api/Byron.hs
Labels: Technical debt

#667 Expose functions and types from `ouroboros-*` required by `cardano-cli`
  cardano-api/cardano-api.cabal
  cardano-api/internal/Cardano/Api/ReexposeConsensus.hs
  cardano-api/internal/Cardano/Api/ReexposeNetwork.hs
  cardano-api/src/Cardano/Api/Consensus.hs
Labels: enhancement
